name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installation (deps and package)
        run: |
          pip install "poetry==1.4.2"
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Run Linters
        run: nox -s lint

      - name: Build
        run: |
          poetry run build-book recipes public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: "./public"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
