name: Linting & Tests

on:
  push:

jobs:
  lint:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run Linters
        run: uv run nox -s lint

      - name: Build
        run: |
          uv run nox -s build
